#
# Dockerfile
#
# this Dockefile is used to build a "base" container image, that is used
# as the basis upon which specific images are then constructed; it ensures
# that there is a "known good" base upon which all images are built.
#

# the base image should offer an essential Ubuntu/Nginx setup
# from which a basic "hello world" index.html page can be delivered
FROM --platform=linux/amd64 nginx:1.25

